module.exports = {
  dbHost: process.env.DB_HOST,
  dbName: process.env.DB_NAME,
  dbUser: process.env.DB_USER,
  dbPass: process.env.DB_PWD,
  jwtSecret: process.env.JWT_KEY,
  refreshSecret: process.env.JWT_REFRESH,
  jwtIssuer: process.env.JWT_ISSUER,
  adminKey: process.env.ADMIN_KEY,
  mService: process.env.MAIL_SERVICE,
  authType: process.env.MAIL_AUTH_TYPE,
  mUser: process.env.MAIL_USER,
  gClientId: process.env.GOOGLE_ID,
  gClientSecret: process.env.GOOGLE_SECRET,
  refreshToken: process.env.REFRESH_TOKEN,
  cloudinaryName: process.env.CLOUDINARY_NAME,
  cloudinaryKey: process.env.CLOUDINARY_KEY,
  cloudinarySecret: process.env.CLOUDINARY_SECRET,
};
